version: '2'

services:
  web:
    build: .
    # command: python DRF_Session_Auth/manage.py runserver 0.0.0.0:8000
    command: >
      bash -c "python DRF_Session_Auth/manage.py migrate
      && python DRF_Session_Auth/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    # depends_on: 
    #   - migration
    environment:
      SESSION_TIMEOUT: 1

  # migration:
  #   build: .
  #   command: python DRF_Session_Auth/manage.py migrate --noinput
  #   volumes:
  #     - .:/code
